# Generated by Django 2.2.7 on 2020-01-03 16:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('PYTHON', 'Python'), ('DJANGO', 'Django'), ('UI', 'ui')], max_length=200)),
                ('trainers', multiselectfield.db.fields.MultiSelectField(choices=[('SAI', 'sai'), ('SATYA', 'satya'), ('ROHIT', 'Rohit')], max_length=200)),
                ('branches', multiselectfield.db.fields.MultiSelectField(choices=[('HYD', 'Hyd'), ('BANG', 'Bang')], max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=100)),
            ],
        ),
    ]
