# Generated by Django 2.2.7 on 2020-01-03 17:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enquiryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirydata',
            name='trainers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SAI', 'sai'), ('SATYA', 'satya'), ('ROHIT', 'rohit')], max_length=200),
        ),
    ]
